// <auto-generated />
namespace TCMS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RoomUpdatedV11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomUpdatedV11));
        
        string IMigrationMetadata.Id
        {
            get { return "201612300745307_Room Updated V1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
